format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$lua\
$jobs\
$battery\
$time\
$line_break\
$status\
$shell\
$character"""

[[battery.display]]
threshold = 30

[character]
error_symbol = "[❯](bold green)"

[directory]
truncation_length = 5
truncation_symbol = "../"

[memory_usage]
disabled = false
format = "[${ram_pct} RAM, ${swap_pct} SWP]($style) "
threshold = 75

[time]
disabled = false
format = "[$time]($style)"
time_format = "%l:%M %p"
use_12hr = true
