# User specific aliases and functions
. ~/.dotfiles/mac/aliases.zsh

setopt histignoredups
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE
export EDITOR=nvim
export PATH="/usr/local/sbin:$PATH"
# Silly Mac, see https://stackoverflow.com/a/41054093
export GPG_TTY=$(tty)

# rust config
export PATH="$HOME/.cargo/bin:$PATH"
export RUST_SRC_PATH="$HOME/.rustup/toolchains/stable-$(uname -m)-apple-darwin/lib/rustlib/src/rust/library"

# postgres
export PATH="/usr/local/opt/postgresql@9.6/bin:$PATH"

# load homebrew completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# autojump config
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# asdf config
. /usr/local/opt/asdf/asdf.sh

# load starship
eval "$(starship init zsh)"
