alias backup="~/.dotfiles/linux/backup.sh"
alias cat="bat -p"
alias gits="git submodule"
alias history="history 1"
alias ls="exa --git --group-directories-first -lgh"
alias rm="rm -v"
alias tether="sudo create_ap --config .tether_conf"
alias update="sudo ~/.dotfiles/linux/update_tools.sh"
alias uuid=uuidgen
alias vim=nvim
