[[battery.display]]
threshold = 30

[character]
error_symbol = "[>](bold green)"

[directory]
truncation_length = 5
truncation_symbol = "../"

[git_branch]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[memory_usage]
disabled = false
format = "[${ram_pct} RAM, ${swap_pct} SWP]($style) "
threshold = 75

[time]
disabled = false
format = "[$time]($style) "
time_format = "%I:%M %p"
use_12hr = true
