# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# User specific aliases and functions
. ~/.dotfiles/linux/aliases.zsh

setopt histignoredups
setopt histignorespace

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE
export EDITOR=nvim
export PAGER=/bin/less
export PATH="$HOME/.local/bin:$PATH"

# rust config
. $HOME/.cargo/env
export RUST_SRC_PATH="$HOME/.rustup/toolchains/stable-$(arch)-unknown-linux-gnu/lib/rustlib/src/rust/library"

# monero
export PATH="$HOME/Crypto/monero-cli:$PATH"

# autojump config
. /usr/share/autojump/autojump.zsh

# asdf config
. $HOME/.asdf/asdf.sh
fpath=(${ASDF_DIR}/completions $fpath)

source ~/.dotfiles/powerlevel10k/powerlevel10k.zsh-theme

autoload -Uz compinit
compinit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
